##
menuADMIN="xpath://ul[@class='oxd-main-menu']/li[1]"
menuPIM="xpath://ul[@class='oxd-main-menu']/li[2]"
menuLEAVE="xpath://ul[@class='oxd-main-menu']/li[3]"
menuTIME="xpath://ul[@class='oxd-main-menu']/li[4]"
menuRecruitment="xpath://ul[@class='oxd-main-menu']/li[5]"
menuMyinfo="xpath://ul[@class='oxd-main-menu']/li[6]"
menuPerformance="xpath://ul[@class='oxd-main-menu']/li[7]"
menuDashboard="xpath://ul[@class='oxd-main-menu']/li[8]"